# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'match_control.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_match_control(object):
    def setupUi(self, match_control):
        match_control.setObjectName("match_control")
        match_control.resize(1200, 900)
        self.tabWidget = QtWidgets.QTabWidget(match_control)
        self.tabWidget.setGeometry(QtCore.QRect(200, 20, 1000, 840))
        self.tabWidget.setObjectName("tabWidget")

        # 任务一
        self.mission1 = QtWidgets.QWidget()
        self.mission1.setObjectName("mission1")
        self.groupBox = QtWidgets.QGroupBox(self.mission1)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(25, 20, 450, 450))
        self.groupBox.setObjectName("groupBox")
        self.Button_random_image1 = QtWidgets.QPushButton(self.groupBox)
        self.Button_random_image1.setGeometry(QtCore.QRect(10, 30, 111, 20))
        self.Button_random_image1.setObjectName("Button_random_image1")
        self.label_status1 = QtWidgets.QLabel(self.groupBox)
        self.label_status1.setGeometry(QtCore.QRect(240, 30, 151, 21))
        self.label_status1.setObjectName("label_status1")
        self.Button_open_image1 = QtWidgets.QPushButton(self.groupBox)
        self.Button_open_image1.setGeometry(QtCore.QRect(140, 30, 101, 20))
        self.Button_open_image1.setObjectName("Button_open_image1")
        self.label_show_image1 = QtWidgets.QLabel(self.groupBox)
        self.label_show_image1.setEnabled(True)
        self.label_show_image1.setGeometry(QtCore.QRect(70, 70, 300, 300))
        self.label_show_image1.setObjectName("label_show_image1")
        self.widget = QtWidgets.QWidget(self.mission1)
        self.widget.setGeometry(QtCore.QRect(25, 500, 950, 300))
        self.widget.setObjectName("widget")
        self.Button_matchstart1 = QtWidgets.QToolButton(self.widget)
        self.Button_matchstart1.setGeometry(QtCore.QRect(400, 50, 131, 71))
        self.Button_matchstart1.setObjectName("Button_matchstart1")
        self.Button_devicerepair1 = QtWidgets.QToolButton(self.widget)
        self.Button_devicerepair1.setGeometry(QtCore.QRect(400, 160, 131, 71))
        self.Button_devicerepair1.setObjectName("Button_devicerepair1")
        self.lcdNumber1 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber1.setGeometry(QtCore.QRect(30, 30, 250, 250))
        self.lcdNumber1.setObjectName("lcdNumber1")
        self.Button_matchstop1 = QtWidgets.QToolButton(self.widget)
        self.Button_matchstop1.setGeometry(QtCore.QRect(600, 50, 131, 71))
        self.Button_matchstop1.setObjectName("Button_matchstop1")
        self.Button_computepoints1 = QtWidgets.QToolButton(self.widget)
        self.Button_computepoints1.setGeometry(QtCore.QRect(600, 160, 131, 71))
        self.Button_computepoints1.setObjectName("Button_computepoints1")
        self.Button_savepoints1 = QtWidgets.QToolButton(self.widget)
        self.Button_savepoints1.setGeometry(QtCore.QRect(800, 160, 131, 71))
        self.Button_savepoints1.setObjectName("Button_savepoints1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.mission1)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 20, 450, 450))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_maichtimes1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_maichtimes1.setGeometry(QtCore.QRect(40, 50, 121, 51))
        self.label_maichtimes1.setObjectName("label_maichtimes1")
        self.label_successin1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_successin1.setGeometry(QtCore.QRect(40, 100, 151, 31))
        self.label_successin1.setObjectName("label_successin1")
        self.label_successtouch1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_successtouch1.setGeometry(QtCore.QRect(40, 150, 151, 31))
        self.label_successtouch1.setObjectName("label_successtouch1")
        self.label_repairtimes1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_repairtimes1.setGeometry(QtCore.QRect(200, 50, 121, 51))
        self.label_repairtimes1.setObjectName("label_repairtimes1")
        self.label_balloutarea1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_balloutarea1.setGeometry(QtCore.QRect(40, 200, 81, 31))
        self.label_balloutarea1.setObjectName("label_balloutarea1")
        self.label_motherballin1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_motherballin1.setGeometry(QtCore.QRect(40, 250, 151, 31))
        self.label_motherballin1.setObjectName("label_motherballin1")
        self.label_touchball1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_touchball1.setGeometry(QtCore.QRect(40, 300, 151, 31))
        self.label_touchball1.setObjectName("label_touchball1")
        self.spinBox_ballsuccessin1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_ballsuccessin1.setGeometry(QtCore.QRect(200, 100, 42, 22))
        self.spinBox_ballsuccessin1.setObjectName("spinBox_ballsuccessin1")
        self.spinBox_touchout1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_touchout1.setGeometry(QtCore.QRect(200, 150, 42, 22))
        self.spinBox_touchout1.setObjectName("spinBox_touchout1")
        self.spinBox_outarea1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_outarea1.setGeometry(QtCore.QRect(200, 200, 42, 22))
        self.spinBox_outarea1.setObjectName("spinBox_outarea1")
        self.spinBox_motherballin1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_motherballin1.setGeometry(QtCore.QRect(200, 250, 42, 22))
        self.spinBox_motherballin1.setObjectName("spinBox_motherballin1")
        self.spinBox_touchball1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_touchball1.setGeometry(QtCore.QRect(200, 300, 42, 22))
        self.spinBox_touchball1.setObjectName("spinBox_touchball1")
        self.label_totalpoints1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_totalpoints1.setGeometry(QtCore.QRect(150, 360, 141, 61))
        self.label_totalpoints1.setObjectName("label_totalpoints1")
        self.tabWidget.addTab(self.mission1, "")

        # 任务二
        self.mission2 = QtWidgets.QWidget()
        self.mission2.setObjectName("mission2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.mission2)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(25, 20, 450, 450))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Button_random_image2 = QtWidgets.QPushButton(self.groupBox_3)
        self.Button_random_image2.setGeometry(QtCore.QRect(10, 30, 111, 20))
        self.Button_random_image2.setObjectName("Button_random_image2")
        self.label_status2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_status2.setGeometry(QtCore.QRect(240, 30, 151, 21))
        self.label_status2.setObjectName("label_status2")
        self.Button_open_image2 = QtWidgets.QPushButton(self.groupBox_3)
        self.Button_open_image2.setGeometry(QtCore.QRect(140, 30, 101, 20))
        self.Button_open_image2.setObjectName("Button_open_image2")
        self.label_show_image2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_show_image2.setEnabled(True)
        self.label_show_image2.setGeometry(QtCore.QRect(70, 70, 300, 300))
        self.label_show_image2.setObjectName("label_show_image2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.mission2)
        self.groupBox_4.setGeometry(QtCore.QRect(520, 20, 450, 450))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_maichtimes2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_maichtimes2.setGeometry(QtCore.QRect(40, 100, 121, 41))
        self.label_maichtimes2.setObjectName("label_maichtimes2")
        self.label_successin2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_successin2.setGeometry(QtCore.QRect(40, 150, 71, 31))
        self.label_successin2.setObjectName("label_successin2")
        self.label_repairtimes2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_repairtimes2.setGeometry(QtCore.QRect(40, 50, 121, 31))
        self.label_repairtimes2.setObjectName("label_repairtimes2")
        self.label_outarea2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_outarea2.setGeometry(QtCore.QRect(40, 200, 81, 31))
        self.label_outarea2.setObjectName("label_outarea2")
        self.label_motherballin2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_motherballin2.setGeometry(QtCore.QRect(40, 250, 81, 31))
        self.label_motherballin2.setObjectName("label_motherballin2")
        self.label_touchball2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_touchball2.setGeometry(QtCore.QRect(40, 300, 81, 31))
        self.label_touchball2.setObjectName("label_touchball2")
        self.comboBox_ballinid2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_ballinid2.setGeometry(QtCore.QRect(200, 150, 91, 22))
        self.comboBox_ballinid2.setObjectName("comboBox_ballinid2")
        self.comboBox_ballinid2.addItem("")
        self.comboBox_ballinid2.addItem("")
        self.comboBox_ballinid2.addItem("")
        self.comboBox_ballinid2.addItem("")
        self.comboBox_ballinid2.addItem("")
        self.comboBox_ballinid2.addItem("")
        self.comboBox_ballinid2.addItem("")
        self.spinBox_outarea2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_outarea2.setGeometry(QtCore.QRect(200, 200, 42, 22))
        self.spinBox_outarea2.setObjectName("spinBox_outarea2")
        self.spinBox_motherballin2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_motherballin2.setGeometry(QtCore.QRect(200, 250, 42, 22))
        self.spinBox_motherballin2.setObjectName("spinBox_motherballin2")
        self.spinBox_touchball2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_touchball2.setGeometry(QtCore.QRect(200, 300, 42, 22))
        self.spinBox_touchball2.setObjectName("spinBox_touchball2")
        self.label_totalpoints2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_totalpoints2.setGeometry(QtCore.QRect(180, 380, 141, 61))
        self.label_totalpoints2.setObjectName("label_totalpoints2")
        self.widget_2 = QtWidgets.QWidget(self.mission2)
        self.widget_2.setGeometry(QtCore.QRect(25, 500, 950, 300))
        self.widget_2.setObjectName("widget_2")
        self.Button_matchstart12 = QtWidgets.QToolButton(self.widget_2)
        self.Button_matchstart12.setGeometry(QtCore.QRect(400, 50, 131, 71))
        self.Button_matchstart12.setObjectName("Button_matchstart12")
        self.Button_devicerepair2 = QtWidgets.QToolButton(self.widget_2)
        self.Button_devicerepair2.setGeometry(QtCore.QRect(400, 160, 131, 71))
        self.Button_devicerepair2.setObjectName("Button_devicerepair2")
        self.Button_matchstop2 = QtWidgets.QToolButton(self.widget_2)
        self.Button_matchstop2.setGeometry(QtCore.QRect(600, 50, 131, 71))
        self.Button_matchstop2.setObjectName("Button_matchstop2")
        self.Button_computepoints2 = QtWidgets.QToolButton(self.widget_2)
        self.Button_computepoints2.setGeometry(QtCore.QRect(600, 160, 131, 71))
        self.Button_computepoints2.setObjectName("Button_computepoints2")
        self.lcdNumber2 = QtWidgets.QLCDNumber(self.widget_2)
        self.lcdNumber2.setGeometry(QtCore.QRect(30, 30, 250, 250))
        self.lcdNumber2.setObjectName("lcdNumber2")
        self.Button_savepoints2 = QtWidgets.QToolButton(self.widget_2)
        self.Button_savepoints2.setGeometry(QtCore.QRect(800, 160, 131, 71))
        self.Button_savepoints2.setObjectName("Button_savepoints2")
        self.tabWidget.addTab(self.mission2, "")

        # 任务三
        self.mission3 = QtWidgets.QWidget()
        self.mission3.setObjectName("mission3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.mission3)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setGeometry(QtCore.QRect(25, 20, 450, 450))
        self.groupBox_5.setObjectName("groupBox_5")
        self.Button_random_image3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Button_random_image3.setGeometry(QtCore.QRect(10, 30, 111, 20))
        self.Button_random_image3.setObjectName("Button_random_image3")
        self.label_status3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_status3.setGeometry(QtCore.QRect(240, 30, 151, 21))
        self.label_status3.setObjectName("label_status3")
        self.Button_open_image3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Button_open_image3.setGeometry(QtCore.QRect(140, 30, 101, 20))
        self.Button_open_image3.setObjectName("Button_open_image3")
        self.label_show_image3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_show_image3.setEnabled(True)
        self.label_show_image3.setGeometry(QtCore.QRect(80, 80, 300, 300))
        self.label_show_image3.setObjectName("label_show_image3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.mission3)
        self.groupBox_6.setGeometry(QtCore.QRect(520, 20, 450, 450))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_maichtimes3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_maichtimes3.setGeometry(QtCore.QRect(40, 50, 121, 51))
        self.label_maichtimes3.setObjectName("label_maichtimes3")
        self.label_successin3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_successin3.setGeometry(QtCore.QRect(40, 100, 151, 31))
        self.label_successin3.setObjectName("label_successin3")
        self.label_successtouch3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_successtouch3.setGeometry(QtCore.QRect(40, 150, 151, 31))
        self.label_successtouch3.setObjectName("label_successtouch3")
        self.label_repairtimes3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_repairtimes3.setGeometry(QtCore.QRect(200, 50, 121, 51))
        self.label_repairtimes3.setObjectName("label_repairtimes3")
        self.label_balloutarea3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_balloutarea3.setGeometry(QtCore.QRect(40, 200, 81, 31))
        self.label_balloutarea3.setObjectName("label_balloutarea3")
        self.label_motherballin3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_motherballin3.setGeometry(QtCore.QRect(40, 250, 151, 31))
        self.label_motherballin3.setObjectName("label_motherballin3")
        self.label_touchball3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_touchball3.setGeometry(QtCore.QRect(40, 300, 151, 31))
        self.label_touchball3.setObjectName("label_touchball3")
        self.spinBox_ballsuccessin3 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_ballsuccessin3.setGeometry(QtCore.QRect(200, 100, 42, 22))
        self.spinBox_ballsuccessin3.setObjectName("spinBox_ballsuccessin3")
        self.spinBox_touchout3 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_touchout3.setGeometry(QtCore.QRect(200, 150, 42, 22))
        self.spinBox_touchout3.setObjectName("spinBox_touchout3")
        self.spinBox_outarea3 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_outarea3.setGeometry(QtCore.QRect(200, 200, 42, 22))
        self.spinBox_outarea3.setObjectName("spinBox_outarea3")
        self.spinBox_motherballin3 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_motherballin3.setGeometry(QtCore.QRect(200, 250, 42, 22))
        self.spinBox_motherballin3.setObjectName("spinBox_motherballin3")
        self.spinBox_touchball3 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_touchball3.setGeometry(QtCore.QRect(200, 300, 42, 22))
        self.spinBox_touchball3.setObjectName("spinBox_touchball3")
        self.label_totalpoints3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_totalpoints3.setGeometry(QtCore.QRect(190, 370, 141, 61))
        self.label_totalpoints3.setObjectName("label_totalpoints3")
        self.widget_3 = QtWidgets.QWidget(self.mission3)
        self.widget_3.setGeometry(QtCore.QRect(25, 500, 950, 300))
        self.widget_3.setObjectName("widget_3")
        self.Button_matchstart3 = QtWidgets.QToolButton(self.widget_3)
        self.Button_matchstart3.setGeometry(QtCore.QRect(400, 50, 131, 71))
        self.Button_matchstart3.setObjectName("Button_matchstart3")
        self.Button_devicerepair3 = QtWidgets.QToolButton(self.widget_3)
        self.Button_devicerepair3.setGeometry(QtCore.QRect(400, 160, 131, 71))
        self.Button_devicerepair3.setObjectName("Button_devicerepair3")
        self.lcdNumber1_2 = QtWidgets.QLCDNumber(self.widget_3)
        self.lcdNumber1_2.setGeometry(QtCore.QRect(30, 30, 250, 250))
        self.lcdNumber1_2.setObjectName("lcdNumber1_2")
        self.Button_matchstop3 = QtWidgets.QToolButton(self.widget_3)
        self.Button_matchstop3.setGeometry(QtCore.QRect(600, 50, 131, 71))
        self.Button_matchstop3.setObjectName("Button_matchstop3")
        self.Button_computepoints3 = QtWidgets.QToolButton(self.widget_3)
        self.Button_computepoints3.setGeometry(QtCore.QRect(600, 160, 131, 71))
        self.Button_computepoints3.setObjectName("Button_computepoints3")
        self.Button_savepoints3 = QtWidgets.QToolButton(self.widget_3)
        self.Button_savepoints3.setGeometry(QtCore.QRect(800, 160, 131, 71))
        self.Button_savepoints3.setObjectName("Button_savepoints3")
        self.tabWidget.addTab(self.mission3, "")

        # 参赛队伍信息栏
        self.groupBox_team_infomation = QtWidgets.QGroupBox(match_control)
        self.groupBox_team_infomation.setGeometry(QtCore.QRect(10, 10, 151, 840))
        self.groupBox_team_infomation.setObjectName("groupBox_team_infomation")
        self.widget_team_infomation = QtWidgets.QWidget(self.groupBox_team_infomation)
        self.widget_team_infomation.setGeometry(QtCore.QRect(10, 40, 130, 261))
        self.widget_team_infomation.setObjectName("widget_team_infomation")
        self.label_partnernumber = QtWidgets.QLabel(self.widget_team_infomation)
        self.label_partnernumber.setGeometry(QtCore.QRect(30, 200, 81, 16))
        self.label_partnernumber.setObjectName("label_partnernumber")
        self.lineEdit_partnernumber = QtWidgets.QLineEdit(self.widget_team_infomation)
        self.lineEdit_partnernumber.setGeometry(QtCore.QRect(30, 230, 81, 20))
        self.lineEdit_partnernumber.setObjectName("lineEdit_partnernumber")
        self.label_id = QtWidgets.QLabel(self.widget_team_infomation)
        self.label_id.setGeometry(QtCore.QRect(30, 10, 71, 31))
        self.label_id.setObjectName("label_id")
        self.label_name = QtWidgets.QLabel(self.widget_team_infomation)
        self.label_name.setGeometry(QtCore.QRect(30, 80, 81, 16))
        self.label_name.setObjectName("label_name")
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget_team_infomation)
        self.lineEdit_name.setGeometry(QtCore.QRect(30, 110, 81, 20))
        self.lineEdit_name.setText("")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_country = QtWidgets.QLabel(self.widget_team_infomation)
        self.label_country.setGeometry(QtCore.QRect(30, 140, 54, 12))
        self.label_country.setObjectName("label_country")
        self.comboBox_country = QtWidgets.QComboBox(self.widget_team_infomation)
        self.comboBox_country.setGeometry(QtCore.QRect(30, 160, 72, 22))
        self.comboBox_country.setObjectName("comboBox_country")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_id = QtWidgets.QComboBox(self.widget_team_infomation)
        self.comboBox_id.setGeometry(QtCore.QRect(30, 40, 72, 22))
        self.comboBox_id.setObjectName("comboBox_id")
        self.comboBox_id.addItem("")
        self.comboBox_id.addItem("")
        self.comboBox_id.addItem("")
        self.comboBox_id.addItem("")
        self.comboBox_id.addItem("")
        self.comboBox_id.addItem("")


        # 赛前信息确认选项
        self.groupBox_infomation_vertify = QtWidgets.QGroupBox(self.groupBox_team_infomation)
        self.groupBox_infomation_vertify.setGeometry(QtCore.QRect(10, 330, 131, 491))
        self.groupBox_infomation_vertify.setObjectName("groupBox_infomation_vertify")
        self.checkBox_partnerinfo = QtWidgets.QCheckBox(self.groupBox_infomation_vertify)
        self.checkBox_partnerinfo.setGeometry(QtCore.QRect(20, 60, 101, 18))
        self.checkBox_partnerinfo.setObjectName("checkBox_partnerinfo")
        self.checkBox_sizeweight = QtWidgets.QCheckBox(self.groupBox_infomation_vertify)
        self.checkBox_sizeweight.setGeometry(QtCore.QRect(20, 180, 101, 18))
        self.checkBox_sizeweight.setObjectName("checkBox_sizeweight")
        self.checkBox_ballclub = QtWidgets.QCheckBox(self.groupBox_infomation_vertify)
        self.checkBox_ballclub.setGeometry(QtCore.QRect(20, 100, 101, 18))
        self.checkBox_ballclub.setObjectName("checkBox_ballclub")
        self.checkBox_workarea = QtWidgets.QCheckBox(self.groupBox_infomation_vertify)
        self.checkBox_workarea.setGeometry(QtCore.QRect(20, 140, 101, 18))
        self.checkBox_workarea.setObjectName("checkBox_workarea")
        self.checkBox_camerainfo = QtWidgets.QCheckBox(self.groupBox_infomation_vertify)
        self.checkBox_camerainfo.setGeometry(QtCore.QRect(20, 220, 101, 18))
        self.checkBox_camerainfo.setObjectName("checkBox_camerainfo")
        self.checkBox_AGVinfo = QtWidgets.QCheckBox(self.groupBox_infomation_vertify)
        self.checkBox_AGVinfo.setGeometry(QtCore.QRect(20, 260, 101, 18))
        self.checkBox_AGVinfo.setObjectName("checkBox_AGVinfo")
        self.checkBox_teamready = QtWidgets.QCheckBox(self.groupBox_infomation_vertify)
        self.checkBox_teamready.setGeometry(QtCore.QRect(20, 310, 101, 18))
        self.checkBox_teamready.setObjectName("checkBox_teamready")
        self.label_teaminfomation = QtWidgets.QLabel(self.groupBox_infomation_vertify)
        self.label_teaminfomation.setGeometry(QtCore.QRect(20, 430, 91, 41))
        self.label_teaminfomation.setObjectName("label_teaminfomation")
        self.toolButton_entermatch = QtWidgets.QToolButton(self.groupBox_infomation_vertify)
        self.toolButton_entermatch.setGeometry(QtCore.QRect(30, 360, 71, 51))
        self.toolButton_entermatch.setObjectName("toolButton_entermatch")

        self.retranslateUi(match_control)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(match_control)

    def retranslateUi(self, match_control):
        _translate = QtCore.QCoreApplication.translate
        match_control.setWindowTitle(_translate("match_control", "Form"))
        self.groupBox.setTitle(_translate("match_control", "随机生成比赛置球方案"))
        self.Button_random_image1.setText(_translate("match_control", "随机生成图片路径"))
        self.label_status1.setText(_translate("match_control", "<html><head/><body><p align=\"center\">状态提示</p></body></html>"))
        self.Button_open_image1.setText(_translate("match_control", "打开置球方案图"))
        self.label_show_image1.setText(_translate("match_control", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\">显示选择的图片</p></body></html>"))
        self.Button_matchstart1.setText(_translate("match_control", "开始"))
        self.Button_devicerepair1.setText(_translate("match_control", "维修"))
        self.Button_matchstop1.setText(_translate("match_control", "结束"))
        self.Button_computepoints1.setText(_translate("match_control", "计分"))
        self.Button_savepoints1.setText(_translate("match_control", "保存"))
        self.groupBox_2.setTitle(_translate("match_control", "过程记录"))
        self.label_maichtimes1.setText(_translate("match_control", "剩余击球次数：5"))
        self.label_successin1.setText(_translate("match_control", "目标球成功入袋："))
        self.label_successtouch1.setText(_translate("match_control", "碰目标球未入袋："))
        self.label_repairtimes1.setText(_translate("match_control", "比赛剩余维修次数：1"))
        self.label_balloutarea1.setText(_translate("match_control", "台球出界："))
        self.label_motherballin1.setText(_translate("match_control", "母球入袋："))
        self.label_touchball1.setText(_translate("match_control", "触碰违例："))
        self.label_totalpoints1.setText(_translate("match_control", "分数："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mission1), _translate("match_control", "定点击球"))
        self.groupBox_3.setTitle(_translate("match_control", "随机生成比赛置球方案"))
        self.Button_random_image2.setText(_translate("match_control", "随机生成图片路径"))
        self.label_status2.setText(_translate("match_control", "<html><head/><body><p align=\"center\">状态提示</p></body></html>"))
        self.Button_open_image2.setText(_translate("match_control", "打开置球方案图"))
        self.label_show_image2.setText(_translate("match_control", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\">显示选择的图片</p></body></html>"))
        self.groupBox_4.setTitle(_translate("match_control", "过程记录"))
        self.label_maichtimes2.setText(_translate("match_control", "剩余击球次数：5"))
        self.label_successin2.setText(_translate("match_control", "最后进袋球:"))
        self.label_repairtimes2.setText(_translate("match_control", "比赛剩余维修次数：1"))
        self.label_outarea2.setText(_translate("match_control", "台球出界："))
        self.label_motherballin2.setText(_translate("match_control", "母球入袋："))
        self.label_touchball2.setText(_translate("match_control", "触碰违例："))
        self.comboBox_ballinid2.setItemText(0, _translate("match_control", "无"))
        self.comboBox_ballinid2.setItemText(1, _translate("match_control", "1号球"))
        self.comboBox_ballinid2.setItemText(2, _translate("match_control", "2号球"))
        self.comboBox_ballinid2.setItemText(3, _translate("match_control", "3号球"))
        self.comboBox_ballinid2.setItemText(4, _translate("match_control", "4号球"))
        self.comboBox_ballinid2.setItemText(5, _translate("match_control", "5号球"))
        self.comboBox_ballinid2.setItemText(6, _translate("match_control", "6号球"))
        self.label_totalpoints2.setText(_translate("match_control", "分数："))
        self.Button_matchstart12.setText(_translate("match_control", "开始"))
        self.Button_devicerepair2.setText(_translate("match_control", "维修"))
        self.Button_matchstop2.setText(_translate("match_control", "结束"))
        self.Button_computepoints2.setText(_translate("match_control", "计分"))
        self.Button_savepoints2.setText(_translate("match_control", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mission2), _translate("match_control", "顺序击球"))
        self.groupBox_5.setTitle(_translate("match_control", "随机生成比赛置球方案"))
        self.Button_random_image3.setText(_translate("match_control", "随机生成图片路径"))
        self.label_status3.setText(_translate("match_control", "<html><head/><body><p align=\"center\">状态提示</p></body></html>"))
        self.Button_open_image3.setText(_translate("match_control", "打开置球方案图"))
        self.label_show_image3.setText(_translate("match_control", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\">显示选择的图片</p></body></html>"))
        self.groupBox_6.setTitle(_translate("match_control", "过程记录"))
        self.label_maichtimes3.setText(_translate("match_control", "剩余击球次数：5"))
        self.label_successin3.setText(_translate("match_control", "目标球成功入袋："))
        self.label_successtouch3.setText(_translate("match_control", "碰目标球未入袋："))
        self.label_repairtimes3.setText(_translate("match_control", "比赛剩余维修次数：1"))
        self.label_balloutarea3.setText(_translate("match_control", "台球出界："))
        self.label_motherballin3.setText(_translate("match_control", "母球入袋："))
        self.label_touchball3.setText(_translate("match_control", "触碰违例："))
        self.label_totalpoints3.setText(_translate("match_control", "分数："))
        self.Button_matchstart3.setText(_translate("match_control", "开始"))
        self.Button_devicerepair3.setText(_translate("match_control", "维修"))
        self.Button_matchstop3.setText(_translate("match_control", "结束"))
        self.Button_computepoints3.setText(_translate("match_control", "计分"))
        self.Button_savepoints3.setText(_translate("match_control", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mission3), _translate("match_control", "动态击球"))
        self.groupBox_team_infomation.setTitle(_translate("match_control", "参赛队伍信息"))
        self.label_partnernumber.setText(_translate("match_control", "队伍人数："))
        self.lineEdit_partnernumber.setText(_translate("match_control", "5"))
        self.label_id.setText(_translate("match_control", "队伍序号："))
        self.label_name.setText(_translate("match_control", "队伍名称："))
        self.label_country.setText(_translate("match_control", "国籍："))
        self.comboBox_country.setCurrentText(_translate("match_control", "无"))
        self.comboBox_country.setItemText(0, _translate("match_control", "无"))
        self.comboBox_country.setItemText(1, _translate("match_control", "德国（Germany）"))
        self.comboBox_country.setItemText(2, _translate("match_control", "中国（China）"))
        self.comboBox_id.setItemText(0, _translate("match_control", "0"))
        self.comboBox_id.setItemText(1, _translate("match_control", "1"))
        self.comboBox_id.setItemText(2, _translate("match_control", "2"))
        self.comboBox_id.setItemText(3, _translate("match_control", "3"))
        self.comboBox_id.setItemText(4, _translate("match_control", "4"))
        self.comboBox_id.setItemText(5, _translate("match_control", "5"))
        self.groupBox_infomation_vertify.setTitle(_translate("match_control", "检查以下信息:"))
        self.checkBox_partnerinfo.setText(_translate("match_control", "参赛人员身份"))
        self.checkBox_sizeweight.setText(_translate("match_control", "装置尺寸质量"))
        self.checkBox_ballclub.setText(_translate("match_control", "击球球杆"))
        self.checkBox_workarea.setText(_translate("match_control", "装置工作范围"))
        self.checkBox_camerainfo.setText(_translate("match_control", "视觉系统正常"))
        self.checkBox_AGVinfo.setText(_translate("match_control", "AGV工作正常"))
        self.checkBox_teamready.setText(_translate("match_control", "队伍准备就绪"))
        self.label_teaminfomation.setText(_translate("match_control", "信息确认无误!"))
        self.toolButton_entermatch.setText(_translate("match_control", "进入比赛"))

